### ISSUE TITLE
Bug in the editing the categories of a product/service

### ISSUE THREAD

**Issue by hadimansouri** [viraweb123/vw-dashboard#18]
In the view of a product/service, if I edit the categories of the product/service an infinite endless progress bar will be shown and the list of categories will not update.
If I refresh the page all I see all the changes are done!

**Comment by mostafabarmshory** [comment]
@hadimansouri 

Would you check the product editor and check the issue, please?

**Comment by hadimansouri** [comment]
Thanks. It is done.
