### ISSUE TITLE
List of bank gates is not shown in the new vw-dashboard

### ISSUE THREAD

**Issue by mostafabarmshory** [viraweb123/vw-dashboard#19]
There is an error in the list.

see https://trello.com/c/6WIPSmxM

**Comment by mostafabarmshory** [comment]
Here is an example page:

    https://elbaan.com/api/v2/bank/backends

**Comment by mostafabarmshory** [comment]
Dear @hadimansouri 

this one is from the server. The list request is faced with the following error:

    {
      "code":1064,
      "status":500,
      "link":null,
      "message":"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') \nLIMIT 30 OFFSET 0' at line 2","data":null}[0.10381900 1598621056] [default] [critical] Fail to handle the request

**Comment by hadimansouri** [comment]
The problem was about the following line of code in the `src6/urls/backend.php`:

``` 
        'params' => array(
            'model' => 'Bank_Backend',
            'sql' => new Pluf_SQL('deleted=%s', array(FALSE))
        )
```

This code makes the following where-clause in the resulted SQL query which has a syntax error:

```SELECT bank_backend.`id` AS `id`, bank_backend.`title` AS `title`, bank_backend.`description` AS `description`, bank_backend.`symbol` AS `symbol`, bank_backend.`home` AS `home`, bank_backend.`redirect` AS `redirect`, bank_backend.`meta` AS `meta`, bank_backend.`engine` AS `engine`, bank_backend.`currency` AS `currency`, bank_backend.`deleted` AS `deleted`, bank_backend.`creation_dtime` AS `creation_dtime`, bank_backend.`modif_dtime` AS `modif_dtime`, bank_backend.`tenant` AS `tenant` FROM bank_backend \nWHERE bank_backend.tenant=1 AND  (deleted=) \nLIMIT 30 OFFSET 0 ```

**Comment by hadimansouri** [comment]
The server-side issue is fixed now (and the online server is fixed manually).
What about client-side?
